version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "CI/CD"
    commit-message:
      prefix: ci

  - directory: proyecto/
    package-ecosystem: npm
    schedule:
      interval: "daily"
    labels:
      - "CI/CD"
      - "Dependencias"
    commit-message:
      prefix: ci
